runtime: python27
api_version: 1
threadsafe: false
default_expiration: "7d"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\(dev\).*$
- ^(.*/)?node_modules$
- ^lib/setuptools$
- ^public
- ^scss
- ^src

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /static
  static_dir: static
- url: (.*)/
  script: apps.main.app

libraries:
- name: webapp2
  version: "latest"
- name: ssl
  version: "latest"
